version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: local-games-postgres
    environment:
      POSTGRES_DB: localgames
      POSTGRES_USER: localgames
      POSTGRES_PASSWORD: localgames123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local-games-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: local-games-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - local-games-network

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: local-games-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=localgames
      - DB_USER=localgames
      - DB_PASSWORD=localgames123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-secret-key-here
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - redis
    networks:
      - local-games-network

  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: local-games-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_WS_URL=ws://localhost:8080/ws
    depends_on:
      - backend
    networks:
      - local-games-network

  # Nginx Reverse Proxy (Production-like)
  nginx:
    image: nginx:alpine
    container_name: local-games-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - local-games-network

volumes:
  postgres_data:
  redis_data:

networks:
  local-games-network:
    driver: bridge 